/**
 * Shell completion generated from the command tree: static scripts that complete subcommands and
 * long options at every level. Good enough for a server tool; no dynamic model-id completion.
 */

import type { CommandSpec } from './command.js'
import { walkCommands } from './command.js'

export type Shell = 'bash' | 'zsh' | 'fish' | 'powershell'
export const SHELLS: readonly Shell[] = ['bash', 'zsh', 'fish', 'powershell']

function wordsFor(spec: CommandSpec): string[] {
  const subs = (spec.subcommands ?? []).filter((s) => !s.hidden).map((s) => s.name)
  const opts = Object.keys(spec.options ?? {}).map((o) => `--${o}`)
  return [...subs, ...opts, '--help', '--json']
}

/** `path` → words, for every node including the root (`''`). */
export function completionTable(root: CommandSpec): Array<[string, string[]]> {
  const table: Array<[string, string[]]> = [['', wordsFor(root)]]
  for (const { spec, path } of walkCommands(root)) {
    if (spec.hidden) continue
    table.push([path.join(' '), wordsFor(spec)])
  }
  return table
}

export function renderCompletion(root: CommandSpec, shell: Shell): string {
  const table = completionTable(root)
  switch (shell) {
    case 'bash':
      return [
        '# atc bash completion — generated by `atc completion bash`',
        '_atc() {',
        '  local cur="${COMP_WORDS[COMP_CWORD]}"',
        '  local path=""',
        '  local i',
        '  for ((i=1; i<COMP_CWORD; i++)); do',
        '    case "${COMP_WORDS[i]}" in -*) ;; *) path="${path:+$path }${COMP_WORDS[i]}" ;; esac',
        '  done',
        '  local words',
        '  case "$path" in',
        ...table.map(([p, w]) => `    "${p}") words="${w.join(' ')}" ;;`),
        '    *) words="" ;;',
        '  esac',
        '  COMPREPLY=( $(compgen -W "$words" -- "$cur") )',
        '}',
        'complete -F _atc atc',
        '',
      ].join('\n')
    case 'zsh':
      return [
        '#compdef atc',
        '# atc zsh completion — generated by `atc completion zsh`',
        '_atc() {',
        '  local -a words_for',
        '  local path=""',
        '  local w',
        '  for w in "${words[@]:1:$((CURRENT-2))}"; do',
        '    case "$w" in -*) ;; *) path="${path:+$path }$w" ;; esac',
        '  done',
        '  case "$path" in',
        ...table.map(([p, w]) => `    "${p}") words_for=(${w.join(' ')}) ;;`),
        '  esac',
        '  compadd -- "${words_for[@]}"',
        '}',
        '_atc "$@"',
        '',
      ].join('\n')
    case 'fish':
      return [
        '# atc fish completion — generated by `atc completion fish`',
        ...table.flatMap(([p, w]) => {
          const condition =
            p === '' ? '__fish_use_subcommand' : `__fish_seen_subcommand_from ${p.split(' ').pop()}`
          return [
            ...w.filter((x) => !x.startsWith('-')).map((x) => `complete -c atc -n '${condition}' -a '${x}'`),
            ...w
              .filter((x) => x.startsWith('--'))
              .map((x) => `complete -c atc -n '${condition}' -l '${x.slice(2)}'`),
          ]
        }),
        '',
      ].join('\n')
    case 'powershell':
      return [
        '# atc PowerShell completion — generated by `atc completion powershell`',
        'Register-ArgumentCompleter -Native -CommandName atc -ScriptBlock {',
        '  param($wordToComplete, $commandAst, $cursorPosition)',
        "  $words = $commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() } | Where-Object { $_ -notlike '-*' }",
        "  $path = ($words | Select-Object -SkipLast 1) -join ' '",
        '  $table = @{',
        ...table.map(([p, w]) => `    '${p}' = @(${w.map((x) => `'${x}'`).join(', ')})`),
        '  }',
        '  $candidates = if ($table.ContainsKey($path)) { $table[$path] } else { @() }',
        '  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {',
        "    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
        '  }',
        '}',
        '',
      ].join('\n')
  }
}
