/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as EnginesIndexRouteImport } from './routes/engines/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesIndexRoute = EnginesIndexRouteImport.update({
  id: '/engines/',
  path: '/engines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/logs': typeof LogsRoute
  '/api/': typeof ApiIndexRoute
  '/engines/': typeof EnginesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/logs': typeof LogsRoute
  '/api': typeof ApiIndexRoute
  '/engines': typeof EnginesIndexRoute
  '/models': typeof ModelsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/logs': typeof LogsRoute
  '/api/': typeof ApiIndexRoute
  '/engines/': typeof EnginesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hardware'
    | '/logs'
    | '/api/'
    | '/engines/'
    | '/models/'
    | '/settings/'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hardware'
    | '/logs'
    | '/api'
    | '/engines'
    | '/models'
    | '/settings'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/hardware'
    | '/logs'
    | '/api/'
    | '/engines/'
    | '/models/'
    | '/settings/'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HardwareRoute: typeof HardwareRoute
  LogsRoute: typeof LogsRoute
  ApiIndexRoute: typeof ApiIndexRoute
  EnginesIndexRoute: typeof EnginesIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines/': {
      id: '/engines/'
      path: '/engines'
      fullPath: '/engines/'
      preLoaderRoute: typeof EnginesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HardwareRoute: HardwareRoute,
  LogsRoute: LogsRoute,
  ApiIndexRoute: ApiIndexRoute,
  EnginesIndexRoute: EnginesIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
